---
- hosts: all
  user: vagrant
  sudo: yes
 
  tasks:
    - name: update apt cache
      apt: update_cache=yes
      
    - name: Install PHP and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - php5
        - libapache2-mod-php5
        
    - name: Install Apache and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2
#        - libapache2-mod-php5
#  handlers:
#    - name: restart apache2
#      service: apache2=ntpd state=restart
