---    
    - name: update apt cache
      apt: update_cache=yes
      
    - name: Install Apache and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2
        - vim
        - mongodb
        - python-pip
        
    - name: Install the latest pymongo package
      pip: name=pymongo state=latest use_mirrors=no 